### ISSUE TITLE
Speeding up network play

### ISSUE THREAD

**Issue by misterjame** [paradust7/minetest-wasm#14]
What kind of work would be required to make network play less laggy? And is this project still actively maintained?

**Comment by paradust7** [comment]
Network play is currently via a websocket proxy that passes all traffic through a single server. The next step up would be to write a networking back-end using WebRTC data channels, which can be direct from clients to servers, or at least distributed geographically like a CDN to minimal lag.

This is a considerable amount of work, and so I'm unlikely to do this soon. This project is on hold while I work on some others.

**Comment by misterjame** [comment]
thank you for the response. great work.
