### ISSUE TITLE
Can not input "I" key in the search field of Inventory window after successful run

### ISSUE THREAD

**Issue by snowyu** [paradust7/minetest-wasm#16]
Pressing the `i` key always toggles the inventory even in the input field. The other binding keys work well.

The [online](https://minetest.dustlabs.io/mt) is ok. I have no idea about this.

```bash
source ~/emsdk/emsdk_env.sh
./apply_patches.sh
./build_all.sh
http-server www --cor 
```

The EMCC version:

```bash
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.18 (d5ca9bba6513763d5bdddbd0efff759332bd85d7)
clang version 16.0.0 (https://github.com/llvm/llvm-project 48129cf0ed5053ed3fdf4f928180635e84892614)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Comment by paradust7** [comment]
Thanks for this report. The online version is 5 months old, so this bug must have been introduced recently. I'll investigate

**Comment by paradust7** [comment]
I've patched in a fix for this in minetest-wasm.
Upstream bug for reference: https://github.com/minetest/minetest/issues/12941
Patch: https://github.com/paradust7/irrlicht/commit/262d3d0151feef2f36944cf785a96e9fc7588034
