### ISSUE TITLE
Cannot connect to other external Rest API except servers.minetest.net

### ISSUE THREAD

**Issue by giangduong** [paradust7/minetest-wasm#19]
Hello,

My mod need to connect to another external rest API. It uses core.get_http_api(). It works fine with Minetest desktop, but failed with this minetest-wasm. Can you please point me how to fix this.

Thanks in advance.

P/S: In my test, with minetest-wasm, the core.get_http_api() can connect to servers.minetest.net, but not others.

**Comment by paradust7** [comment]
This is a security feature. The proxy can only access servers.minetest.net and content.minetest.net

**Comment by TamaMcGlinn** [comment]
However, if you set up a server, the mod code runs on the server, and then your web client can just connect to that.
