### ISSUE TITLE
Libjpeg build fails: jchuff.c error invalid token at start SIZEOF_SIZE_T 

### ISSUE THREAD

**Issue by TamaMcGlinn** [paradust7/minetest-wasm#21]
When trying to build, libjpeg fails with the following error. I also [opened an issue in libjpeg](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/21), but I suspect the problem belongs here rather than there.

The problem might also be solved by putting the version of emsdk that you succesfully used in the README.

```
/home/tama/code/computercraft/minetest-wasm/sources/libjpeg/jchuff.c:92:46: error: invalid token at start of a preprocessor expression
#if (defined(SIZEOF_SIZE_T) && SIZEOF_SIZE_T == 8) || defined(_WIN64) || \
                                             ^
/home/tama/code/computercraft/minetest-wasm/sources/libjpeg/jchuff.c:95:48: error: invalid token at start of a preprocessor expression
#elif (defined(SIZEOF_SIZE_T) && SIZEOF_SIZE_T == 4) || defined(_WIN32)
                                               ^
/home/tama/code/computercraft/minetest-wasm/sources/libjpeg/jchuff.c:98:2: error: Cannot determine word size
#error Cannot determine word size
 ^
```

I have tried different commits for libjpeg, and adding a definition for SIZEOF_SIZE_T to CMakeLists.txt (line 8) as follows, but got the same result:

```
set(SIZEOF_SIZE_T 8)
```

**Comment by paradust7** [comment]
The project is using a pinned version of libjpeg, so it can't be a problem there. It's most likely due to a change in emsdk.

I'll investigate. I'll see if I can pin the version of emsdk too, to improve stability.

**Comment by paradust7** [comment]
@TamaMcGlinn There seems to have been some major refactoring which broke cmake compatibility with pthreads. The fix will not be quick.

For now, I suggest installing and activating emsdk 3.1.25 instead of the latest (which is 3.1.28). This should fix it:

```
cd emsdk
./emsdk install 3.1.25
./emsdk activate 3.1.25
source ./emsdk_env.sh
```

You'll need to reapply the emsdk patches too.

**Comment by TamaMcGlinn** [comment]
Thank you very much; that fixed it.
