### ISSUE TITLE
SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by Paul2009-38** [paradust7/minetest-wasm#22]
I ran your program, there was an error I could see in the chrome dev console: Uncaught ReferenceError: SharedArrayBuffer is not defined at minetest.js:1:7364

**Comment by Paul2009-38** [comment]
I solved my problem by putting an ssl https certificate but I'm stuck at step: wasm_module task: 0%

**Comment by paradust7** [comment]
Are there any errors in the Javascript console?

**Comment by Paul2009-38** [comment]
At first sight there is no error but i think the apache2 wasm module was installed incorrectly

**Comment by TamaMcGlinn** [comment]
@qupoja Can you elaborate on "by putting an ssl https certificate" ? I'm getting this error, and I used to fix it by starting chrome with a flag to enable SharedArrayBuffer (`google-chrome --enable-features=SharedArrayBuffer`), but it no longer works.
