### ISSUE TITLE
Game "Glitch" loads wrong mapgen

### ISSUE THREAD

**Issue by Wuzzy2** [paradust7/minetest-wasm#28]
The game named "Glitch" does not work as intended.

It seems this game starts with the valleys mapgen because at the beginning, there is an error saying that the river water mapgen alias is missing. This error message can only be triggered by the valleys mapgen. Glitch must run with the singlenode mapgen tho.

Note that Glitch's code itself does not force a mapgen but game.conf only allows singlenode via allowed_mapgens.

Apart from that, Glitch seems to run fine although the version on the website looks outdated as the game has some bugs that are fixed in the latest release.

(Tested on <https://minetest.dustlabs.io/> on date  22/09/2023)

**Comment by paradust7** [comment]
This has been fixed in the repo and will be fixed with the next site update.
