### ISSUE TITLE
Could it be used to load a personal map, or does it need a server ?

### ISSUE THREAD

**Issue by papiche** [paradust7/minetest-wasm#30]
Wishing to load maps from https://minecraft.ign.fr/
I wonder how I could use minetest-dust the best way ?

**Comment by MadKamel** [comment]
Minecraft or Minetest?

**Comment by papiche** [comment]
Minetest

**Comment by papiche** [comment]
Hi @MadKamel 
Could it be able to load a 100x100 cube word, with one cube in the center in "creative mode" and be saved in any way ?
We would like to build a Web3 app based on Minetest... Please contact support@qo-op.com

**Comment by paradust7** [comment]
If you compile and host it yourself, you can do whatever you want. You could include a pre-packaged map, or write your own game/mod to generate a map. You could enable creative mode. You'll need to read index.html and launcher.js to understand how to do this.

This is minetest so it won't be able to read minecraft maps. But there are unofficial converters that might work for you.
