### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by osherifo** [paradust7/minetest-wasm#39]
Hello @paradust7 I am working at a research institute and we would like to use this software to research human machine interaction experiments, It would be really beneficial if a license was added so we could use it freely. Let me know if you want to learn more about our research.

**Comment by MisterE123** [comment]
you mean like this: https://github.com/paradust7/minetest-wasm/blob/main/LICENSE ?

**Comment by osherifo** [comment]
yes thanks :D
