### ISSUE TITLE
The mods I downloaded in the game have disappeared

### ISSUE THREAD

**Issue by lychees** [paradust7/minetest-wasm#5]
Hi, thanks for the share, this is the warehouse I've been looking for for a long time!

I ran the game on chrome on windows 10 and downloaded the mods within the game today, but when I refreshed, the downloaded mods disappeared. Is this an intended behavior and how to fix it?
Regards.

**Comment by paradust7** [comment]
There's no file system storage on web pages. Every time you refresh the page, it starts from scratch.
You could add your mods to the built-in file system by modifying `build_fsroot.sh`.
