### ISSUE TITLE
Bug report: Unable to join server with ip address

### ISSUE THREAD

**Issue by lychees** [paradust7/minetest-wasm#6]
Unable to join server with ip address.

Running on chrome on windows 10.

When joining a server using an ip address, the game gets stuck and an error occurs on the console.
![Q2](https://user-images.githubusercontent.com/2507027/169357192-af7861d7-03dc-4bca-853a-ac336f606112.png)

And using a domain address to join the server will join normally.

**Comment by paradust7** [comment]
I'll have a fix for this in a few days

**Comment by paradust7** [comment]
This should be fixed now. The dustlabs.io proxy server will allow connections to any server that talks the correct protocol.
