### ISSUE TITLE
Feature request: Join a server directly via URL parameters

### ISSUE THREAD

**Issue by lychees** [paradust7/minetest-wasm#8]
E.g.
https://minetest.dustlabs.io/mt/?address=192.168.0.1&port=30000&account=foo&pwd=bar

**Comment by paradust7** [comment]
You can add extra command-line arguments to:

https://github.com/paradust7/minetest-wasm/blob/main/static/index.html#L174

Such as `--address`, `--port`, `--name`, `--password`, `--go`
