### ISSUE TITLE
Client crashed after a player using a Bike.

### ISSUE THREAD

**Issue by lychees** [paradust7/minetest-wasm#9]
![image](https://user-images.githubusercontent.com/2507027/171936598-4a3422e7-d91a-474e-879c-52ae1c420d2c.png)

https://content.minetest.net/packages/Hume2/bike/

Whenever a player using a bike, all wasm client got crashed, (while other player who using native client is unaffected)
Although it is related with a specific mod, I think it might be a general problem with websockets synchronization.

**Comment by paradust7** [comment]
I need more information. What browser(s)? Are there any messages in the javascript console? Does it happen in single player mode?

**Comment by paradust7** [comment]
not enough info to reproduce
